### ISSUE TITLE
Aposthrophes "'" in file names break the script.

### ISSUE THREAD

**Issue by DL6AKU** [DL6AKU/kcwebm#1]
This does not work:

    $ kcwebm.py -s 10 -r 480 -x9 Don\'t\ Give\ Up.mkv
    /temp/akurei/Don\'t\ Give\ Up.mkv
    /temp/akurei/Don\'t\ Give\ Up.webm
    /bin/sh: -c: line 0: unexpected EOF while looking for matching `''
    /bin/sh: -c: line 1: syntax error: unexpected end of file
    ffprobe -v quiet -of csv=p=0 -show_entries format=duration /temp/akurei/Don\'t\ Give\ Up.mkv
    Traceback (most recent call last):
      File "/home/akurei/.userscripts/bin//kcwebm.py", line 156, in <module>
        main()
      File "/home/akurei/.userscripts/bin//kcwebm.py", line 148, in main
        encode_cmd = get_encode_cmd(args)
      File "/home/akurei/.userscripts/bin//kcwebm.py", line 115, in get_encode_cmd
        cmd = cmd.replace("@RATE@", "{!s}k".format(calc_rate(args, inpath)))
      File "/home/akurei/.userscripts/bin//kcwebm.py", line 59, in calc_rate
        raise RuntimeError("Unable to get stream duration. Return code != 0")
    RuntimeError: Unable to get stream duration. Return code != 0

**Comment by DL6AKU** [comment]
Probably use this to fix:

https://stackoverflow.com/questions/14928860/passing-double-quote-shell-commands-in-python-to-subprocess-popen

**Comment by DL6AKU** [comment]
Does not Fix #1. Remembered that badly. I though spaces were the problem, not apostrophes. So this is still open.
